### ISSUE TITLE
sinon-test is not restoring stubs on ES6 class with static method

### ISSUE THREAD

**Issue by StylishFlash** [sinonjs/sinon-test#101]
Versions used:

- node: 8.10.0
- sinon: 7.2.7
- sinon-test: 2.4.0
- mocha: 6.0.2

Also using:

- typescript: 3.3.3333
- ts-node: 8.0.2

But I think this is unrelated to the problem.

Class with static method that we want to stub:
````
class MyClass {
    static myMethod() {
        return "originalReturn";
    }
}
export default MyClass;
````
sandbox.spec.ts:
````
import * as sinon from "sinon";
import MyClass from "../src/myClass";

const sinonTest = require("sinon-test");
const test = sinonTest(sinon);

describe("sandbox", function() {

    it("test 1", test(function() {
        sinon.stub(MyClass, "myMethod");
    }));

    it("test 2", test(function() {
        sinon.stub(MyClass, "myMethod");
    }));

});
````
Running with mocha throws:
````
1) sandbox
       test 2:
     TypeError: Attempted to wrap myMethod which is already wrapped
      at checkWrappedMethod (node_modules\sinon\lib\sinon\util\core\wrap-method.js:39:21)
      at wrapMethod (node_modules\sinon\lib\sinon\util\core\wrap-method.js:87:13)
      at stub (node_modules\sinon\lib\sinon\stub.js:73:44)
      at Sandbox.stub (node_modules\sinon\lib\sinon\sandbox.js:291:33)
      at Context.<anonymous> (test\sandbox.spec.ts:17:15)
      at callSandboxedFn (node_modules\sinon-test\lib\test.js:93:25)
      at Context.sinonSandboxedTest (node_modules\sinon-test\lib\test.js:113:24)
  --------------
  Error: Stack Trace for original
      at wrapMethod (node_modules\sinon\lib\sinon\util\core\wrap-method.js:112:30)
      at stub (node_modules\sinon\lib\sinon\stub.js:73:44)
      at Sandbox.stub (node_modules\sinon\lib\sinon\sandbox.js:291:33)
      at Context.<anonymous> (test\sandbox.spec.ts:13:15)
      at callSandboxedFn (node_modules\sinon-test\lib\test.js:93:25)
      at Context.sinonSandboxedTest (node_modules\sinon-test\lib\test.js:113:24)
````
However when using the sandbox directly without sinon-test the tests pass:
````
import * as sinon from "sinon";
import {SinonSandbox} from "sinon";
import MyClass from "../src/myClass";

describe("sandbox", function() {

    it("test 1", function() {
        const sandbox: SinonSandbox = sinon.createSandbox();
        sandbox.stub(MyClass, "myMethod");
        sandbox.restore();
    });

    it("test 2", function() {
        const sandbox: SinonSandbox = sinon.createSandbox();
        sandbox.stub(MyClass, "myMethod");
        sandbox.restore();
    });

});
````
Behaviour seems to be similar to this old Sinon issue: [#878](https://github.com/sinonjs/sinon/issues/878)

**Comment by fatso83** [comment]
Great bug report! I'll look into it.

**Comment by fatso83** [comment]
Verified: https://runkit.com/fatso83/sinon-test-issue-101

**Comment by fatso83** [comment]
Ha, I couldn't believe I didn't see what was wrong. I knew it was something very basic, since this is _the most basic usecase_: restoring a stub on an object, which is covered by several tests. 

Basically, it's a user error :-) This:
```javascript
        sinon.stub(MyClass, "myMethod");
```

should look like this:
```javascript
        this.stub(MyClass, "myMethod");
```

**Comment by StylishFlash** [comment]
Ohhh, I've completely overread that part of the documentation. That means I have been using it wrong all this time and wasn't even running my past tests within an actual sandbox lol. Got it working now. Thanks for the quick reply.
