### ISSUE TITLE
Incompatible/all tests fail using Sinon > 7.3.0

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon-test#118]
Our peerDependencies says this is compatible with Sinon 7.x, but if we use minor version 7.3 (and above) all sinon-test internal tests fail.

To reproduce, clone the repo and do this:
```
npm i sinon@7.3 && npm t; # will fail

npm i sinon@7.2.4 && npm t; # will pass
```

<details>
<summary>Output from failling tests</summary>

```

> sinon-test@2.4.0 test /home/carlerik/dev/sinon-test
> mocha



  ✓ throws if argument is not a function
  ✓ proxies return value
  1) stubs inside sandbox
  2) restores stubs
  3) restores stubs on all object methods
  ✓ throws when method throws
  ✓ throws when an async method throws
  ✓ restores stub after promise resolves
  4) restores stub after promise is resolved
  5) restores stub after promise is rejected
  6) returns the test's promise even if the test function has parameters (e.g. assert in QUnit)
  ✓ restores stub when method throws
  7) mocks inside sandbox
  ✓ passes on errors to callbacks
  ✓ async test with sandbox
  ✓ async test with sandbox using mocha interface
  ✓ async test with sandbox using mocha interface throwing error
  8) async test with sandbox and spy
  ✓ async test preserves additional args and pass them in correct order
  ✓ async tests should allow thenables to be returned without a callback function
  ✓ async tests should not allow thenables to be returned with a callback function
  9) verifies mocks
  ✓ restores mocks
  ✓ restores mock when method throws
  ✓ appends helpers after normal arguments
  ✓ maintains the this value
  sync tests with thenable return value
    10) should listen to returned promise
    11) restores sandbox after promise is fulfilled
    12) restores sandbox after promise is rejected
    13) ensures test rejects with a non-falsy value

  sync tests with A+ promise returned
    14) restores the sandbox when the promise is fulfilled
    ✓ restores the sandbox when the promise is rejected
    ✓ ensures test rejects with a non-falsy value
    ✓ re-throws the error if the promise is rejected
    15) verifies mocks when promise is resolved

  configurable test with sandbox
    ✓ yields stub, mock as arguments
    ✓ yields spy, stub, mock as arguments
    ✓ does not yield server when not faking xhr
    ✓ yields clock when faking timers
    ✓ fakes specified timers
    16) injects properties into test case
    17) injects functions into test case by default
    18) injects sandbox
    ✓ remove injected properties afterwards
    19) uses test to fake time
    backwards compatibility
      ✓ uses the new factory methods introduced in 3.1 - if available
      ✓ falls back to the old 1.x-2.x methods when needed 
    browser options
      ✓ yields server when faking xhr
      ✓ uses serverWithClock when faking xhr
      ✓ injects properties into object
      20) injects server and clock when only enabling them


  31 passing (4s)
  20 failing

  1) stubs inside sandbox:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:87:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.stubs inside sandbox (test/test-test.js:90:12)
      at processImmediate (internal/timers.js:439:21)

  2) restores stubs:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:98:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.restores stubs (test/test-test.js:99:12)
      at processImmediate (internal/timers.js:439:21)

  3) restores stubs on all object methods:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:110:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.restores stubs on all object methods (test/test-test.js:111:12)
      at processImmediate (internal/timers.js:439:21)

  4) restores stub after promise is resolved:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:161:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.restores stub after promise is resolved (test/test-test.js:165:12)
      at processImmediate (internal/timers.js:439:21)

  5) restores stub after promise is rejected:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:179:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.restores stub after promise is rejected (test/test-test.js:183:12)
      at processImmediate (internal/timers.js:439:21)

  6) returns the test's promise even if the test function has parameters (e.g. assert in QUnit):
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:198:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonAsyncSandboxedTest (lib/test.js:110:24)
      at Context.returns the test's promise even if the test function has parameters (e.g. assert in QUnit) (test/test-test.js:202:12)
      at processImmediate (internal/timers.js:439:21)

  7) mocks inside sandbox:
     TypeError: this.mock is not a function
      at Object.<anonymous> (test/test-test.js:228:18)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.mocks inside sandbox (test/test-test.js:231:12)
      at processImmediate (internal/timers.js:439:21)

  8) async test with sandbox and spy:
     TypeError: this.spy is not a function
      at Object.<anonymous> (test/test-test.js:311:39)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonAsyncSandboxedTest (lib/test.js:110:24)
      at Context.async test with sandbox and spy (test/test-test.js:319:12)
      at processImmediate (internal/timers.js:439:21)

  9) verifies mocks:
     AssertionError: [assert.same] TypeError expected to be the same object as ExpectationError
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:160:21)
      at Object.fail (node_modules/@sinonjs/referee/lib/referee.js:49:17)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:57:17)
      at Function.referee.<computed>.<computed> [as same] (node_modules/@sinonjs/referee/lib/referee.js:77:19)
      at Context.verifies mocks (test/test-test.js:545:16)
      at processImmediate (internal/timers.js:439:21)

  10) sync tests with thenable return value
       should listen to returned promise:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:363:22)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.should listen to returned promise (test/test-test.js:378:42)
      at processImmediate (internal/timers.js:439:21)

  11) sync tests with thenable return value
       restores sandbox after promise is fulfilled:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:363:22)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.restores sandbox after promise is fulfilled (test/test-test.js:394:42)
      at processImmediate (internal/timers.js:439:21)

  12) sync tests with thenable return value
       restores sandbox after promise is rejected:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:363:22)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.restores sandbox after promise is rejected (test/test-test.js:402:42)
      at processImmediate (internal/timers.js:439:21)

  13) sync tests with thenable return value
       ensures test rejects with a non-falsy value:
     TypeError: this.stub is not a function
      at Object.<anonymous> (test/test-test.js:363:22)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.ensures test rejects with a non-falsy value (test/test-test.js:417:42)
      at processImmediate (internal/timers.js:439:21)

  14) sync tests with A+ promise returned
       restores the sandbox when the promise is fulfilled:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/carlerik/dev/sinon-test/test/test-test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  15) sync tests with A+ promise returned
       verifies mocks when promise is resolved:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/carlerik/dev/sinon-test/test/test-test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  16) configurable test with sandbox
       injects properties into test case:
     AssertionError: [assert.equals] 1 expected to be equal to 0
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:160:21)
      at Object.fail (node_modules/@sinonjs/referee/lib/referee.js:49:17)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:57:17)
      at Function.referee.<computed>.<computed> [as equals] (node_modules/@sinonjs/referee/lib/referee.js:77:19)
      at Object.testFunction (test/test-test.js:863:24)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.injects properties into test case (test/test-test.js:870:40)
      at processImmediate (internal/timers.js:439:21)

  17) configurable test with sandbox
       injects functions into test case by default:
     AssertionError: [assert.equals] 11 expected to be equal to 0
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:160:21)
      at Object.fail (node_modules/@sinonjs/referee/lib/referee.js:49:17)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:57:17)
      at Function.referee.<computed>.<computed> [as equals] (node_modules/@sinonjs/referee/lib/referee.js:77:19)
      at Object.testFunction (test/test-test.js:875:24)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.injects functions into test case by default (test/test-test.js:882:36)
      at processImmediate (internal/timers.js:439:21)

  18) configurable test with sandbox
       injects sandbox:
     AssertionError: [assert.equals] 2 expected to be equal to 0
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:160:21)
      at Object.fail (node_modules/@sinonjs/referee/lib/referee.js:49:17)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:57:17)
      at Function.referee.<computed>.<computed> [as equals] (node_modules/@sinonjs/referee/lib/referee.js:77:19)
      at Object.testFunction (test/test-test.js:887:24)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.injects sandbox (test/test-test.js:898:40)
      at processImmediate (internal/timers.js:439:21)

  19) configurable test with sandbox
       uses test to fake time:
     TypeError: this.spy is not a function
      at Object.<anonymous> (test/test-test.js:925:36)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest [as test] (lib/test.js:113:24)
      at Context.uses test to fake time (test/test-test.js:933:22)
      at processImmediate (internal/timers.js:439:21)

  20) configurable test with sandbox
       browser options
         injects server and clock when only enabling them:
     AssertionError: [assert.equals] 11 expected to be equal to 0
      at referee.fail (node_modules/@sinonjs/referee/lib/referee.js:160:21)
      at Object.fail (node_modules/@sinonjs/referee/lib/referee.js:49:17)
      at assertion (node_modules/@sinonjs/referee/lib/referee.js:57:17)
      at Function.referee.<computed>.<computed> [as equals] (node_modules/@sinonjs/referee/lib/referee.js:77:19)
      at Object.testFunction (test/test-test.js:784:28)
      at callSandboxedFn (lib/test.js:93:25)
      at Object.sinonSandboxedTest (lib/test.js:113:24)
      at Context.injects server and clock when only enabling them (test/test-test.js:794:44)
      at processImmediate (internal/timers.js:439:21)
```

</details>

Seeing that the failing tests involve configuration, I assume this is related to #102

**Comment by fatso83** [comment]
I'm guessing this is related to the changes in the default config in Sinon 7.3. https://github.com/sinonjs/sinon-test/issues/102#issuecomment-474823698
